### ISSUE TITLE
[Build-linux] GCC version should be increase

### ISSUE THREAD

**Issue by ErwanDouaille** [sofa-framework/doc#11]
I tried compiling sofa on ubuntu 16.04 with gcc 4.8.5m but we encounter errors related to advance timer.
I think the "SOFA requires at least GCC 4.8 or Clang 3.4." should be updated.

**Comment by ErwanDouaille** [comment]
`FAILED: SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/AdvancedTimer.cpp.o 
/usr/bin/g++-4.8   -DNDEBUG -DSofaHelper_EXPORTS -I/tmp/sofa/SofaKernel/framework/sofa/helper/../.. -isystem /tmp/sofa/SofaKernel/extlibs/eigen-3.2.7 -Iinclude -I/tmp/sofa/SofaKernel/extlibs/tinyxml -Wall -W -O3 -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC   -DSOFA_BUILD_HELPER -std=gnu++11 -MD -MT SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/AdvancedTimer.cpp.o -MF SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/AdvancedTimer.cpp.o.d -o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/AdvancedTimer.cpp.o -c /tmp/sofa/SofaKernel/framework/sofa/helper/AdvancedTimer.cpp
In file included from /tmp/sofa/SofaKernel/framework/sofa/helper/../../../extlibs/json/json.h:5:0,
                 from /tmp/sofa/SofaKernel/framework/sofa/helper/AdvancedTimer.cpp:30:
/tmp/sofa/SofaKernel/framework/sofa/helper/../../../extlibs/json/nlohmann_json.h:66:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"`

I also tried 4.9 and having this issue :  
`FAILED: lib/libSofaHelper.so.17.12.dev 
: && /usr/bin/g++-4.9  -fPIC -Wall -W -O3 -DNDEBUG -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2  -Wl,--no-undefined -lc -shared -Wl,-soname,libSofaHelper.so.17.12.dev -o lib/libSofaHelper.so.17.12.dev SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/AdvancedTimer.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/ArgumentParser.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/BackTrace.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/ColorMap.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/DualQuat.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/Factory.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/GenerateRigid.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/LCPcalc.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/MarchingCubeUtility.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/OptionsGroup.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/StateMask.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/SVector.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/Polynomial_LD.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/Quater.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/RandomGenerator.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/TagFactory.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/UnitTest.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/Utils.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/decompose.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/deprecatedcomponents.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Trackball.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Transformation.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/init.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/BaseFileAccess.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/FileAccess.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/File.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/Image.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/ImageDDS.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/ImageRAW.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MassSpringLoader.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/Mesh.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MeshOBJ.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MeshSTL.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MeshTopologyLoader.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MeshTrian.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/MeshVTK.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/SphereLoader.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/TriangleLoader.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/bvh/BVHJoint.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/bvh/BVHLoader.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/io/bvh/BVHMotion.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/kdTree.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/polygon_cube_intersection/fast_polygon_cube_intersection.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/polygon_cube_intersection/polygon_cube_intersection.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/proximity.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/DynamicLibrary.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/FileSystem.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/Locale.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/PipeProcess.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/PluginManager.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/SetDirectory.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/SofaOStream.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/console.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/thread/CTime.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/thread/CircularQueue.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/thread/debug.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/FileRepository.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/vector.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/types/fixed_array.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/types/RGBAColor.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/types/Material.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/Message.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/MessageDispatcher.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/ComponentInfo.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/ClangMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/ClangStyleMessageFormatter.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/DefaultStyleMessageFormatter.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/ConsoleMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/SilentMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/FileMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/CountingMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/LoggingMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/RoutingMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/logging/ExceptionMessageHandler.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/FileMonitor_linux.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Axis.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/BasicShapesGL.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Cylinder.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/glText.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Capture.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Texture.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/Color.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/glfont.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/gl.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/FrameBufferObject.cpp.o SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/gl/GLSLShader.cpp.o  -Wl,-rpath,/tmp/build-sofa-Desktop_Qt_5_9_1_GCC4_9_64bit-Default/lib: -ldl -lX11 -lGLU -lGL /usr/lib/x86_64-linux-gnu/libGLEW.so /usr/lib/x86_64-linux-gnu/libglut.so lib/libtinyxml.so.2.6.2 /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libboost_system.so /usr/lib/x86_64-linux-gnu/libboost_locale.so /usr/lib/x86_64-linux-gnu/libboost_filesystem.so /usr/lib/x86_64-linux-gnu/libboost_date_time.so /usr/lib/x86_64-linux-gnu/libboost_thread.so -lboost_system -lboost_filesystem -lboost_locale -lboost_thread -lboost_date_time -lboost_chrono -lboost_atomic -lpthread && :
SofaKernel/SofaFramework/SofaHelper/CMakeFiles/SofaHelper.dir/system/FileRepository.cpp.o: In function `sofa::helper::system::FileRepository::findFileIn(std::string&, std::string const&)':
FileRepository.cpp:(.text+0x3d6): undefined reference to `boost::locale::generator::generate(std::string const&) const'
collect2: error: ld returned 1 exit status`

Works well with 5.0

**Comment by guparan** [comment]
Thanks for the report @ErwanDouaille. json lib integration indeed bumped all compilers minimal version. 
About GCC 4.9 error, did you investigate?

**Comment by ErwanDouaille** [comment]
@guparan for 4.9 no, I tought it was due to something else, but I will (this friday).
